---
    name: Execução Manual
    on:
      workflow_dispatch: null
    jobs:
      e2e-tests:
        runs-on:
          - ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Instalando Yarn
            run: npm install -g yarn
          - name: Instalando dependências
            run: yarn
          - name: Instalando Playwright
            run: yarn playwright install
          - name: Testes E2E (end-to-end)
            run: yarn run e2e